//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFe.Repositories.DownloadNFe {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeDownloadNF", ConfigurationName="DownloadNFe.NfeDownloadNFSoap")]
    public interface NfeDownloadNFSoap {
        
        // CODEGEN: Generating message contract since the operation nfeDownloadNF is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NfeDownloadNF/nfeDownloadNF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NFe.Repositories.DownloadNFe.nfeDownloadNFResponse nfeDownloadNF(NFe.Repositories.DownloadNFe.nfeDownloadNFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NfeDownloadNF/nfeDownloadNF", ReplyAction="*")]
        System.Threading.Tasks.Task<NFe.Repositories.DownloadNFe.nfeDownloadNFResponse> nfeDownloadNFAsync(NFe.Repositories.DownloadNFe.nfeDownloadNFRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeDownloadNF")]
    public partial class nfeCabecMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versaoDadosField;
        
        private string cUFField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string versaoDados {
            get {
                return this.versaoDadosField;
            }
            set {
                this.versaoDadosField = value;
                this.RaisePropertyChanged("versaoDados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string cUF {
            get {
                return this.cUFField;
            }
            set {
                this.cUFField = value;
                this.RaisePropertyChanged("cUF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeDownloadNFRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeDownloadNF")]
        public NFe.Repositories.DownloadNFe.nfeCabecMsg nfeCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeDownloadNF", Order=0)]
        public System.Xml.XmlNode nfeDadosMsg;
        
        public nfeDownloadNFRequest() {
        }
        
        public nfeDownloadNFRequest(NFe.Repositories.DownloadNFe.nfeCabecMsg nfeCabecMsg, System.Xml.XmlNode nfeDadosMsg) {
            this.nfeCabecMsg = nfeCabecMsg;
            this.nfeDadosMsg = nfeDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeDownloadNFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeDownloadNF", Order=0)]
        public System.Xml.XmlNode nfeDownloadNFResult;
        
        public nfeDownloadNFResponse() {
        }
        
        public nfeDownloadNFResponse(System.Xml.XmlNode nfeDownloadNFResult) {
            this.nfeDownloadNFResult = nfeDownloadNFResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NfeDownloadNFSoapChannel : NFe.Repositories.DownloadNFe.NfeDownloadNFSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NfeDownloadNFSoapClient : System.ServiceModel.ClientBase<NFe.Repositories.DownloadNFe.NfeDownloadNFSoap>, NFe.Repositories.DownloadNFe.NfeDownloadNFSoap {
        
        public NfeDownloadNFSoapClient() {
        }
        
        public NfeDownloadNFSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NfeDownloadNFSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NfeDownloadNFSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NfeDownloadNFSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NFe.Repositories.DownloadNFe.nfeDownloadNFResponse NFe.Repositories.DownloadNFe.NfeDownloadNFSoap.nfeDownloadNF(NFe.Repositories.DownloadNFe.nfeDownloadNFRequest request) {
            return base.Channel.nfeDownloadNF(request);
        }
        
        public System.Xml.XmlNode nfeDownloadNF(NFe.Repositories.DownloadNFe.nfeCabecMsg nfeCabecMsg, System.Xml.XmlNode nfeDadosMsg) {
            NFe.Repositories.DownloadNFe.nfeDownloadNFRequest inValue = new NFe.Repositories.DownloadNFe.nfeDownloadNFRequest();
            inValue.nfeCabecMsg = nfeCabecMsg;
            inValue.nfeDadosMsg = nfeDadosMsg;
            NFe.Repositories.DownloadNFe.nfeDownloadNFResponse retVal = ((NFe.Repositories.DownloadNFe.NfeDownloadNFSoap)(this)).nfeDownloadNF(inValue);
            return retVal.nfeDownloadNFResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NFe.Repositories.DownloadNFe.nfeDownloadNFResponse> NFe.Repositories.DownloadNFe.NfeDownloadNFSoap.nfeDownloadNFAsync(NFe.Repositories.DownloadNFe.nfeDownloadNFRequest request) {
            return base.Channel.nfeDownloadNFAsync(request);
        }
        
        public System.Threading.Tasks.Task<NFe.Repositories.DownloadNFe.nfeDownloadNFResponse> nfeDownloadNFAsync(NFe.Repositories.DownloadNFe.nfeCabecMsg nfeCabecMsg, System.Xml.XmlNode nfeDadosMsg) {
            NFe.Repositories.DownloadNFe.nfeDownloadNFRequest inValue = new NFe.Repositories.DownloadNFe.nfeDownloadNFRequest();
            inValue.nfeCabecMsg = nfeCabecMsg;
            inValue.nfeDadosMsg = nfeDadosMsg;
            return ((NFe.Repositories.DownloadNFe.NfeDownloadNFSoap)(this)).nfeDownloadNFAsync(inValue);
        }
    }
}
