//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFe.Repositories.ConsultaCadastroNFe {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro2", ConfigurationName="ConsultaCadastroNFe.CadConsultaCadastro2Soap")]
    public interface CadConsultaCadastro2Soap {
        
        // CODEGEN: Generating message contract since the operation consultaCadastro2 is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro2/consultaCadastro2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NFe.Repositories.ConsultaCadastroNFe.consultaCadastro2Response consultaCadastro2(NFe.Repositories.ConsultaCadastroNFe.consultaCadastro2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro2/consultaCadastro2", ReplyAction="*")]
        System.Threading.Tasks.Task<NFe.Repositories.ConsultaCadastroNFe.consultaCadastro2Response> consultaCadastro2Async(NFe.Repositories.ConsultaCadastroNFe.consultaCadastro2Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro2")]
    public partial class nfeCabecMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versaoDadosField;
        
        private string cUFField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string versaoDados {
            get {
                return this.versaoDadosField;
            }
            set {
                this.versaoDadosField = value;
                this.RaisePropertyChanged("versaoDados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string cUF {
            get {
                return this.cUFField;
            }
            set {
                this.cUFField = value;
                this.RaisePropertyChanged("cUF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaCadastro2Request {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro2")]
        public NFe.Repositories.ConsultaCadastroNFe.nfeCabecMsg nfeCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro2", Order=0)]
        public System.Xml.XmlNode nfeDadosMsg;
        
        public consultaCadastro2Request() {
        }
        
        public consultaCadastro2Request(NFe.Repositories.ConsultaCadastroNFe.nfeCabecMsg nfeCabecMsg, System.Xml.XmlNode nfeDadosMsg) {
            this.nfeCabecMsg = nfeCabecMsg;
            this.nfeDadosMsg = nfeDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaCadastro2Response {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro2")]
        public NFe.Repositories.ConsultaCadastroNFe.nfeCabecMsg nfeCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro2", Order=0)]
        public System.Xml.XmlNode consultaCadastro2Result;
        
        public consultaCadastro2Response() {
        }
        
        public consultaCadastro2Response(NFe.Repositories.ConsultaCadastroNFe.nfeCabecMsg nfeCabecMsg, System.Xml.XmlNode consultaCadastro2Result) {
            this.nfeCabecMsg = nfeCabecMsg;
            this.consultaCadastro2Result = consultaCadastro2Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CadConsultaCadastro2SoapChannel : NFe.Repositories.ConsultaCadastroNFe.CadConsultaCadastro2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CadConsultaCadastro2SoapClient : System.ServiceModel.ClientBase<NFe.Repositories.ConsultaCadastroNFe.CadConsultaCadastro2Soap>, NFe.Repositories.ConsultaCadastroNFe.CadConsultaCadastro2Soap {
        
        public CadConsultaCadastro2SoapClient() {
        }
        
        public CadConsultaCadastro2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CadConsultaCadastro2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CadConsultaCadastro2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CadConsultaCadastro2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NFe.Repositories.ConsultaCadastroNFe.consultaCadastro2Response NFe.Repositories.ConsultaCadastroNFe.CadConsultaCadastro2Soap.consultaCadastro2(NFe.Repositories.ConsultaCadastroNFe.consultaCadastro2Request request) {
            return base.Channel.consultaCadastro2(request);
        }
        
        public System.Xml.XmlNode consultaCadastro2(ref NFe.Repositories.ConsultaCadastroNFe.nfeCabecMsg nfeCabecMsg, System.Xml.XmlNode nfeDadosMsg) {
            NFe.Repositories.ConsultaCadastroNFe.consultaCadastro2Request inValue = new NFe.Repositories.ConsultaCadastroNFe.consultaCadastro2Request();
            inValue.nfeCabecMsg = nfeCabecMsg;
            inValue.nfeDadosMsg = nfeDadosMsg;
            NFe.Repositories.ConsultaCadastroNFe.consultaCadastro2Response retVal = ((NFe.Repositories.ConsultaCadastroNFe.CadConsultaCadastro2Soap)(this)).consultaCadastro2(inValue);
            nfeCabecMsg = retVal.nfeCabecMsg;
            return retVal.consultaCadastro2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NFe.Repositories.ConsultaCadastroNFe.consultaCadastro2Response> NFe.Repositories.ConsultaCadastroNFe.CadConsultaCadastro2Soap.consultaCadastro2Async(NFe.Repositories.ConsultaCadastroNFe.consultaCadastro2Request request) {
            return base.Channel.consultaCadastro2Async(request);
        }
        
        public System.Threading.Tasks.Task<NFe.Repositories.ConsultaCadastroNFe.consultaCadastro2Response> consultaCadastro2Async(NFe.Repositories.ConsultaCadastroNFe.nfeCabecMsg nfeCabecMsg, System.Xml.XmlNode nfeDadosMsg) {
            NFe.Repositories.ConsultaCadastroNFe.consultaCadastro2Request inValue = new NFe.Repositories.ConsultaCadastroNFe.consultaCadastro2Request();
            inValue.nfeCabecMsg = nfeCabecMsg;
            inValue.nfeDadosMsg = nfeDadosMsg;
            return ((NFe.Repositories.ConsultaCadastroNFe.CadConsultaCadastro2Soap)(this)).consultaCadastro2Async(inValue);
        }
    }
}
